pub mod analyze;
pub mod analyzed_kanji_node;
pub mod arc_len;
pub mod bbox;
pub mod centroid;
pub mod convert_lossy;
pub mod convert_stroke_index;
pub mod dtw;
pub mod gen_svg;
pub mod kanji_node;
pub mod leaf_matrix;
pub mod map_space_to;
pub mod match_strokes;
pub mod normalize;
pub mod rdp;
pub mod recognize_character;
pub mod recognize_hiragana;
pub mod recognize_kanji;
pub mod recognizer;
pub mod recognizer2;
pub mod stroke_geometry;
pub mod stroke_point;
pub mod stroke_window;
pub mod to_bez_path;
pub mod to_index;
pub mod transform;
use std::collections::HashMap;

use crate::kanji_node::KanjiNode;

pub type KanjiMap = HashMap<char, KanjiNode>;
