pub mod analyze;
pub mod analyzed_kanji_node;
pub mod arc_len;
pub mod assignment;
pub mod bbox;
pub mod centroid;
pub mod convert_lossy;
pub mod convert_stroke_index;
pub mod gen_svg;
pub mod group_score;
pub mod kanji_node;
pub mod leaf_matrix;
pub mod leaf_score;
pub mod map_space_to;
pub mod match_strokes;
pub mod merge_variants;
pub mod normalize;
pub mod rdp;
pub mod recognizer;
pub mod shape;
pub mod stroke_geometry;
pub mod stroke_point;
pub mod stroke_window;
pub mod to_bez_path;
pub mod to_index;
pub mod transform;
pub mod weights;
use std::collections::HashMap;

use crate::kanji_node::KanjiNode;

pub type KanjiMap = HashMap<char, KanjiNode>;
