[package]
name = "japanese-input"
version = "0.2.0"
edition = "2024"

[dependencies]
kurbo={ version = "0.13",features = ["serde"]}
dtw_rs = "0.10"
ordered-float = "5"
pathfinding = "4"
serde = { version = "1", features = ["derive"] }
smallvec = "1"
svg = "0.18"
colorous = "1.0"
postcard = { version = "1", features = ["alloc"] }
rayon = "1.12.0"

[dev-dependencies]
rand = "0.10.2"
criterion = "0.8"


[[bench]]
name = "match_bench"
harness = false

[[bench]]
name = "recognizer_bench"
harness = false

[lints]
workspace = true
