use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use pulldown_cmark::{Event, Options, Parser, Tag, TagEnd, html};

/// The tuned model, generated locally under `data/generated/` in this same repo (see the root `.gitignore`'s own allowlist — that path is already excluded there, same protection as the defense-in-depth denylist below). Used automatically for `dx serve`/`cargo check` so recognition can be tested locally with zero setup — only the *compiled* `OUT_DIR` copy ever embeds it, same as the CI path below.
const LOCAL_DEFAULT_MODEL_PATH: &str = "../data/generated/recognizer2_tuned.bin";

/// Regenerated by `cargo test tests::generate_reference_data` (in `../kanji-vg`), same as `build_bins.yml` does for the addon itself — never committed here, so it must exist locally (run that command once) or be freshly generated in CI before this crate builds.
const REFERENCE_DATA_PATH: &str = "../data/generated/reference_data.bin";

/// The repo's own media (screenshots etc.), mirrored into `assets/media` on every build so the home page's embedded README can reference them. Never committed here (see .gitignore) — always copied fresh, same freshness guarantee as the README text itself.
const MEDIA_SOURCE_DIR: &str = "../media";
const MEDIA_DEST_DIR: &str = "assets/media";

/// Rendering markdown to HTML only ever needs to happen once, at build time, since the source file only changes when the addon's own readme.md does — doing it here instead of at runtime in `home.rs` keeps `pulldown-cmark` out of the shipped wasm entirely (it's a build-dependency, not a dependency).
const ADDON_README_PATH: &str = "../readme.md";

fn main() {
    println!("cargo:rerun-if-env-changed=RECOGNIZER_MODEL_PATH");
    println!("cargo:rerun-if-changed={LOCAL_DEFAULT_MODEL_PATH}");
    println!("cargo:rerun-if-changed={REFERENCE_DATA_PATH}");
    println!("cargo:rerun-if-changed={MEDIA_SOURCE_DIR}");
    println!("cargo:rerun-if-changed={ADDON_README_PATH}");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));

    fs::copy(REFERENCE_DATA_PATH, out_dir.join("reference_data.bin")).unwrap_or_else(|e| {
        panic!(
            "failed to read {REFERENCE_DATA_PATH}: {e}\n\
             Generate it first: (cd .. && cargo test tests::generate_reference_data)"
        )
    });

    let dest = out_dir.join("recognizer_model.bin");

    let source = env::var("RECOGNIZER_MODEL_PATH").ok().or_else(|| {
        Path::new(LOCAL_DEFAULT_MODEL_PATH)
            .exists()
            .then(|| LOCAL_DEFAULT_MODEL_PATH.to_owned())
    });

    match source {
        Some(path) => {
            println!("cargo:warning=embedding recognizer model from {path}");
            fs::copy(&path, &dest)
                .unwrap_or_else(|e| panic!("failed to copy recognizer model from {path}: {e}"));
        }
        None => {
            // No model available anywhere: embed an empty placeholder so the crate still compiles. `Recognizer::load` on empty bytes returns `Err`, which the recognition page treats as "not available in this build".
            fs::write(&dest, []).expect("failed to write placeholder recognizer model");
        }
    }

    let media_source = Path::new(MEDIA_SOURCE_DIR);
    if media_source.is_dir() {
        let media_dest = Path::new(MEDIA_DEST_DIR);
        fs::create_dir_all(media_dest).expect("failed to create assets/media");
        copy_dir_recursive(media_source, media_dest);
    }

    render_readme(&out_dir);
}

/// Splits the addon's README around its one embedded image (`media/back.png`) and renders each half to HTML, so `HomePage` can splice in the real bundled asset in its place instead of a dead link into the addon repo — same split `home.rs` used to do at runtime, just moved here.
fn render_readme(out_dir: &Path) {
    let markdown = fs::read_to_string(ADDON_README_PATH)
        .unwrap_or_else(|e| panic!("failed to read {ADDON_README_PATH}: {e}"));

    let mut options = Options::empty();
    options.insert(Options::ENABLE_TABLES);
    let parser = Parser::new_ext(&markdown, options);

    let mut before = Vec::new();
    let mut after = Vec::new();
    let mut past_image = false;
    let mut in_image = false;
    for event in parser {
        match event {
            Event::Start(Tag::Image { .. }) => {
                in_image = true;
                past_image = true;
                continue;
            }
            Event::End(TagEnd::Image) => {
                in_image = false;
                continue;
            }
            _ if in_image => continue,
            event if past_image => after.push(event),
            event => before.push(event),
        }
    }

    let mut before_html = String::new();
    html::push_html(&mut before_html, before.into_iter());
    let mut after_html = String::new();
    html::push_html(&mut after_html, after.into_iter());

    fs::write(out_dir.join("readme_before.html"), before_html)
        .expect("failed to write readme_before.html");
    fs::write(out_dir.join("readme_after.html"), after_html)
        .expect("failed to write readme_after.html");
}

fn copy_dir_recursive(src: &Path, dest: &Path) {
    for entry in fs::read_dir(src)
        .unwrap_or_else(|e| panic!("failed to read directory {}: {e}", src.display()))
    {
        let entry = entry.expect("failed to read directory entry");
        let src_path = entry.path();
        let dest_path = dest.join(entry.file_name());
        let file_type = entry.file_type().expect("failed to read file type");
        if file_type.is_dir() {
            fs::create_dir_all(&dest_path).expect("failed to create media subdirectory");
            copy_dir_recursive(&src_path, &dest_path);
        } else {
            fs::copy(&src_path, &dest_path).unwrap_or_else(|e| {
                panic!(
                    "failed to copy {} to {}: {e}",
                    src_path.display(),
                    dest_path.display()
                )
            });
        }
    }
}
