name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: generate reference data
      run: cargo test tests::generate_reference_data
    - name: generate hiragana reference data
      run: cargo test tests::generate_hiragana
    - name: generate kanji reference data
      run: cargo test tests::generate_kanji
    - name: Checkout model repo
      uses: actions/checkout@v4
      with:
        repository: Drodofsky/regonizer-model
        token: ${{ secrets.model }}
        path: model-repo
    - name: download recognizer model
      run: cp model-repo/recognizer2_tuned.bin data/generated/recognizer2_tuned.bin
    - name: Run tests
      run: cargo test --verbose
